name: supercharge_delta_lake
description: ''
version: '77.0'
author: maciej+webinar-2022@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: supercharge_delta_lake
  parentArtefactID: prophecy_webinar
  buildSystem: wheel
  author: null
  createdAt: '2023-03-24 19:20:44'
pipelines:
  pipelines/ingest_customers:
    name: ingest_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:19:30'
    datasets:
      inputs:
      - datasets/raw_customers
      outputs:
      - datasets/bronze_customers
    subgraphs: []
    dependencies: {}
  pipelines/cleanup_customers:
    name: cleanup_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:33:01'
    datasets:
      inputs:
      - datasets/bronze_customers
      outputs:
      - datasets/silver_customers
    subgraphs: []
    dependencies: {}
  pipelines/mrr_reporting:
    name: mrr_reporting
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-10-11 23:15:32'
    datasets:
      inputs:
      - datasets/customer_nations
      - datasets/nation
      - datasets/regions
      - datasets/silver_customers
      - datasets/silver_orders
      outputs:
      - datasets/final_report
    subgraphs:
    - subgraphs/enrich_customers
    dependencies: {}
  pipelines/cleanup_orders:
    name: cleanup_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:31:06'
    datasets:
      inputs:
      - 3436/datasets/bronze_orders
      outputs:
      - 3436/datasets/silver_orders
    subgraphs: []
    dependencies: {}
  pipelines/demo_day:
    name: demo_day
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-02-23 18:44:09'
    datasets:
      inputs:
      - datasets/customer_nations
      - datasets/nation
      - datasets/regions
      - datasets/silver_customers
      - datasets/silver_orders
      outputs:
      - datasets/final_table
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customer_nations:
    name: customer_nations
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:37:12'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:37:12'
  datasets/regions:
    name: regions
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:35:00'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:35:00'
  datasets/report_gold:
    name: report_gold
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-07 04:03:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-07 04:03:31'
  datasets/report:
    name: report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-24 16:12:02'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Warehouse
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-24 16:12:02'
  datasets/raw_customers:
    name: raw_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:28:34'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:28:34'
  datasets/raw_orders:
    name: raw_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:30:06'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:30:06'
  datasets/gold_report:
    name: gold_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-04 16:02:40'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-04 16:02:40'
  datasets/final_report:
    name: final_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-11 23:29:28'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-11 23:29:29'
  datasets/silver_orders:
    name: silver_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:32:05'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:32:05'
  datasets/orders_merge:
    name: orders_merge
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-11-09 16:35:17'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-11-09 16:35:17'
  datasets/nation:
    name: nation
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:35:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:35:31'
  datasets/silver_customers:
    name: silver_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:33:40'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:33:40'
  datasets/bronze_customers:
    name: bronze_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:27:10'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:27:10'
  datasets/bronze_orders:
    name: bronze_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:30:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:30:31'
  datasets/maciej_customer_spendings:
    name: maciej_customer_spendings
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-01-30 23:31:14'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-01-30 23:31:14'
  datasets/final_table:
    name: final_table
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-02-23 18:52:08'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-02-23 18:52:08'
  datasets/text_input:
    name: text_input
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-07 04:18:52'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-07 04:18:53'
  datasets/silver_orders_1:
    name: silver_orders_1
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-04 15:53:56'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-04 15:53:56'
  datasets/silvers_orders_1:
    name: silvers_orders_1
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-11 23:22:30'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-11 23:22:30'
  datasets/silver_customers_2:
    name: silver_customers_2
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-05 16:31:43'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-05 16:31:43'
  datasets/silver_orders_3:
    name: silver_orders_3
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-07 03:55:20'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-07 03:55:20'
  datasets/qwe:
    name: qwe
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-01-31 06:33:38'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Warehouse
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-01-31 06:33:38'
  datasets/random_data:
    name: random_data
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-01 20:12:37'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-01 20:12:37'
  datasets/configurable_report:
    name: configurable_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-13 20:27:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-13 20:27:58'
  datasets/test_qwe:
    name: test_qwe
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-28 07:15:47'
    mode: batch
    physicalDatasets:
      dev_e2:
        fabricId: 1618
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-28 07:15:48'
  datasets/test_1:
    name: test_1
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-06-28 07:17:29'
    mode: batch
    physicalDatasets:
      dev_e2:
        fabricId: 1618
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-06-28 07:17:29'
templates: {}
jobs:
  jobs/daily_job:
    name: daily_job
    description: ''
    fabricUID: 1618
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: maciej@prophecy.io
      onStart: true
      onSuccess: false
      onFailure: true
    pipelines:
    - pipelines/cleanup_orders
    - pipelines/cleanup_customers
    - pipelines/mrr_reporting
    - pipelines/ingest_customers
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2022-09-29 01:34:28'
    author: maciej+webinar-2022@prophecy.io
  jobs/daily_prod_job:
    name: daily_prod_job
    description: ''
    fabricUID: 1132
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/ingest_customers
    - pipelines/ingest_orders
    - pipelines/cleanup_customers
    - pipelines/mrr_reporting
    - pipelines/cleanup_orders
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2022-10-27 16:49:30'
    author: maciej+webinar-admin-2022@prophecy.io
  jobs/monthly_schedule:
    name: monthly_schedule
    description: ''
    fabricUID: 1034
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/demo_day
    - pipelines/cleanup_customers
    - pipelines/cleanup_orders
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-02-23 18:53:26'
    author: maciej+webinar-2022@prophecy.io
  jobs/airflow_test:
    name: airflow_test
    description: ''
    fabricUID: 3346
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0/1 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-07-14 05:56:17'
    author: maciej@prophecy.io
  jobs/monthly_job:
    name: monthly_job
    description: ''
    fabricUID: 1618
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/mrr_reporting
    - pipelines/cleanup_orders
    - pipelines/cleanup_customers
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-07-20 21:47:10'
    author: maciej@prophecy.io
functions:
  author: null
  createdAt: '2023-03-24 19:20:44'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs:
  subgraphs/enrich_customers:
    name: enrich_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2022-09-29 03:48:30'
  subgraphs/customers_orders:
    name: customers_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2022-12-14 21:18:35'
  subgraphs/data_cleanup:
    name: data_cleanup
    description: ''
    author: maciej+webinar-2022@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2023-02-17 04:35:57'
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
