name: supercharge_delta_lake
description: ''
version: '80.0'
author: maciej+webinar-2022@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: supercharge_delta_lake
  parentArtefactID: prophecy_webinar
  buildSystem: wheel
  author: null
  createdAt: '2023-03-24 19:20:44'
pipelines:
  pipelines/ingest_customers:
    name: ingest_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:19:30'
    datasets:
      inputs:
      - datasets/raw_customers
      outputs:
      - datasets/bronze_customers
    subgraphs: []
    dependencies: {}
  pipelines/cleanup_customers:
    name: cleanup_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:33:01'
    datasets:
      inputs:
      - datasets/bronze_customers
      outputs:
      - datasets/silver_customers
    subgraphs: []
    dependencies: {}
  pipelines/cleanup_orders:
    name: cleanup_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:31:06'
    datasets:
      inputs:
      - datasets/bronze_orders
      outputs:
      - datasets/silver_orders
    subgraphs: []
    dependencies: {}
  pipelines/mrr_reporting:
    name: mrr_reporting
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-10-11 23:15:32'
    datasets:
      inputs:
      - datasets/silver_customers
      - datasets/silver_orders
      - gitUri=http://gitserver:3000/qaBmFHEl_team_4097/M2yhwd8U_project_data_enrichment.git&subPath=/&tag=data_enrichment/1.2&projectSubscriptionProjectId=16366&path=datasets/customer_nations
      - gitUri=http://gitserver:3000/qaBmFHEl_team_4097/M2yhwd8U_project_data_enrichment.git&subPath=/&tag=data_enrichment/1.2&projectSubscriptionProjectId=16366&path=datasets/nation
      - gitUri=http://gitserver:3000/qaBmFHEl_team_4097/M2yhwd8U_project_data_enrichment.git&subPath=/&tag=data_enrichment/1.2&projectSubscriptionProjectId=16366&path=datasets/regions
      outputs: []
    subgraphs:
    - gitUri=http://gitserver:3000/qaBmFHEl_team_4097/M2yhwd8U_project_data_enrichment.git&subPath=/&tag=data_enrichment/1.2&projectSubscriptionProjectId=16366&path=subgraphs/enrich_customers
    dependencies: {}
  pipelines/mrr_reporting_2:
    name: mrr_reporting_2
    description: ''
    author: maciej@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-21 23:07:58'
    datasets:
      inputs:
      - datasets/bronze_customers
      - datasets/bronze_orders
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customer_nations:
    name: customer_nations
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:37:12'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:37:12'
  datasets/raw_customers:
    name: raw_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:28:34'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:28:34'
  datasets/silver_orders:
    name: silver_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:32:05'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:32:05'
  datasets/silver_customers:
    name: silver_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:33:40'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:33:40'
  datasets/bronze_customers:
    name: bronze_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:27:10'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:27:10'
  datasets/bronze_orders:
    name: bronze_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:30:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:30:31'
  datasets/test:
    name: test
    description: ''
    author: maciej@prophecy.io
    createdAt: '2024-09-05 01:12:09'
    mode: batch
    physicalDatasets:
      dev_e2:
        fabricId: 1618
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2024-09-05 01:12:09'
  datasets/default_customer:
    name: default_customer
    description: ''
    author: maciej@prophecy.io
    createdAt: '2024-09-05 01:13:44'
    mode: batch
    physicalDatasets:
      dev_e2:
        fabricId: 1618
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2024-09-05 01:13:44'
  datasets/test2:
    name: test2
    description: ''
    author: maciej@prophecy.io
    createdAt: '2024-09-05 01:40:38'
    mode: batch
    physicalDatasets:
      guides_dev_anon:
        fabricId: 17040
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2024-09-05 01:40:38'
templates: {}
jobs:
  jobs/monthly_job_db:
    name: monthly_job_db
    description: ''
    fabricUID: 1618
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/ingest_customers
    - pipelines/cleanup_orders
    - pipelines/cleanup_customers
    - pipelines/mrr_reporting
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2023-08-08 19:30:30'
    author: maciej@prophecy.io
    models: []
    sqlProjects: []
  jobs/monthly_job_airflow:
    name: monthly_job_airflow
    description: ''
    fabricUID: 3346
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 1 * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/ingest_customers
    - pipelines/cleanup_orders
    - pipelines/mrr_reporting
    - pipelines/cleanup_customers
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2023-08-08 19:31:06'
    author: maciej@prophecy.io
    models: []
    sqlProjects: []
  jobs/daily_schedule:
    name: daily_schedule
    description: ''
    fabricUID: 1618
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/mrr_reporting
    - pipelines/cleanup_orders
    - pipelines/cleanup_customers
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-12-07 18:42:02'
    author: maciej@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-03-24 19:20:44'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-08-21T23:07:59.892694Z'
  name: plibMaven
  version: 8.0.31
  id: '1331718660'
  createdAt: '2024-08-21T23:07:59.892661Z'
- type: plibPypi
  modifiedAt: '2024-08-21T23:07:59.892736Z'
  name: plibPypi
  version: 1.9.9
  id: '881602919'
  createdAt: '2024-08-21T23:07:59.892727Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.7
    isDefault: true
    author: null
    createdAt: '2023-12-06 05:06:59'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-09-28 08:42:10'
  '16366':
    projectUID: 16366
    projectName: data_enrichment
    repositoryPath: gitUri=http://gitserver:3000/qaBmFHEl_team_4097/M2yhwd8U_project_data_enrichment.git&subPath=/
    version: data_enrichment/1.2
    isDefault: false
    author: null
    createdAt: '2024-09-05 20:11:32'
  '32699':
    projectUID: 32699
    projectName: ProphecySparkDataQualityPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/gLsx7fee_project_32699.git&subPath=
    version: 0.0.1
    isDefault: false
    author: null
    createdAt: '2024-09-06 01:21:37'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
