name: supercharge_delta_lake
description: ''
version: '81.0'
author: maciej+webinar-2022@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: supercharge_delta_lake
  parentArtefactID: prophecy_webinar
  buildSystem: wheel
  author: null
  createdAt: '2023-03-24 19:20:44'
pipelines:
  pipelines/mrr_reporting:
    name: mrr_reporting
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-10-11 23:15:32'
    datasets:
      inputs:
      - datasets/customers_new
      outputs:
      - datasets/test_output
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customer_nations:
    name: customer_nations
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:37:12'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:37:12'
  datasets/regions:
    name: regions
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:35:00'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:35:00'
  datasets/report_gold:
    name: report_gold
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-07 04:03:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-07 04:03:31'
  datasets/report:
    name: report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-24 16:12:02'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Warehouse
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-24 16:12:02'
  datasets/raw_customers:
    name: raw_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:28:34'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:28:34'
  datasets/raw_orders:
    name: raw_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:30:06'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:30:06'
  datasets/gold_report:
    name: gold_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-04 16:02:40'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-04 16:02:40'
  datasets/silver_orders:
    name: silver_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:32:05'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:32:05'
  datasets/silver_customers:
    name: silver_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:33:40'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:33:40'
  datasets/bronze_customers:
    name: bronze_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:27:10'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:27:10'
  datasets/bronze_orders:
    name: bronze_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:30:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:30:31'
  datasets/department_table:
    name: department_table
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-08-30 04:58:20'
    mode: batch
    physicalDatasets:
      dev_e2:
        fabricId: 1618
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-08-30 04:58:20'
  datasets/final_report:
    name: final_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-11 23:29:28'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-11 23:29:29'
  datasets/test_output:
    name: test_output
    description: ''
    author: maciej@prophecy.io
    createdAt: '2024-08-07 21:32:44'
    mode: batch
    physicalDatasets:
      db_product:
        fabricId: 1777
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2024-08-07 21:32:44'
  datasets/customers_new:
    name: customers_new
    description: ''
    author: maciej@prophecy.io
    createdAt: '2024-08-07 21:43:48'
    mode: batch
    physicalDatasets:
      db_product:
        fabricId: 1777
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2024-08-07 21:43:48'
templates: {}
jobs:
  jobs/2024_08_07_vanilla_schedule_test:
    name: 2024_08_07_vanilla_schedule_test
    description: ''
    fabricUID: 1777
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0/1 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2024-08-08 01:48:23'
    author: maciej@prophecy.io
    models: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/Limit2:
      name: Limit2
      category: Transform
      subCategory: ''
      description: null
      author: maciej@prophecy.io
      mode: batch
      files:
      - prophecy_webinar_supercharge_delta_lake/gems/Limit2.py
      gemType: ComponentGem
      dependencies: null
      createdAt: '2024-01-30 21:59:43'
    gems/CubeGem:
      name: CubeGem
      category: Transform
      subCategory: ''
      description: null
      author: maciej@prophecy.io
      mode: batch
      files:
      - prophecy_webinar_supercharge_delta_lake/gems/CubeGem.py
      gemType: ComponentGem
      dependencies: null
      createdAt: '2024-02-01 19:27:23'
  dependencies: null
functions:
  author: null
  createdAt: '2023-03-24 19:20:44'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-06-08T18:20:38.296353Z'
  name: plibMaven
  version: 8.0.29
  id: '963836732'
  createdAt: '2024-06-08T18:20:38.296324Z'
  enabled: true
  entity: Project
- type: plibPypi
  modifiedAt: '2024-06-08T18:20:38.296587Z'
  name: plibPypi
  version: 1.9.9
  id: '2037754521'
  createdAt: '2024-06-08T18:20:38.296571Z'
  enabled: true
  entity: Project
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-08-07 21:07:05'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-08-07 21:07:09'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
