name: supercharge_delta_lake
description: ''
version: '78.0'
author: maciej+webinar-2022@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: supercharge_delta_lake
  parentArtefactID: prophecy_webinar
  buildSystem: wheel
  author: null
  createdAt: '2023-03-24 19:20:44'
pipelines:
  pipelines/ingest_customers:
    name: ingest_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:19:30'
    datasets:
      inputs:
      - datasets/raw_customers
      outputs:
      - datasets/bronze_customers
    subgraphs: []
    dependencies: {}
  pipelines/cleanup_customers:
    name: cleanup_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:33:01'
    datasets:
      inputs:
      - datasets/bronze_customers
      outputs:
      - datasets/silver_customers
    subgraphs: []
    dependencies: {}
  pipelines/cleanup_orders:
    name: cleanup_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:31:06'
    datasets:
      inputs:
      - datasets/bronze_orders
      outputs:
      - datasets/silver_orders
    subgraphs: []
    dependencies: {}
  pipelines/mrr_reporting:
    name: mrr_reporting
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-10-11 23:15:32'
    datasets:
      inputs:
      - datasets/customer_nations
      - datasets/nation
      - datasets/regions
      - datasets/silver_customers
      - datasets/silver_orders
      outputs:
      - datasets/final_report
    subgraphs:
    - subgraphs/enrich_customers
    dependencies: {}
datasets:
  datasets/customer_nations:
    name: customer_nations
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:37:12'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:37:12'
  datasets/regions:
    name: regions
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:35:00'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:35:00'
  datasets/raw_customers:
    name: raw_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:28:34'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:28:34'
  datasets/raw_orders:
    name: raw_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:30:06'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:30:06'
  datasets/final_report:
    name: final_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-11 23:29:28'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-11 23:29:29'
  datasets/silver_orders:
    name: silver_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:32:05'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:32:05'
  datasets/nation:
    name: nation
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:35:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:35:31'
  datasets/silver_customers:
    name: silver_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:33:40'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:33:40'
  datasets/bronze_customers:
    name: bronze_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:27:10'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:27:10'
  datasets/bronze_orders:
    name: bronze_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:30:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:30:31'
templates: {}
jobs:
  jobs/monthly_job_db:
    name: monthly_job_db
    description: ''
    fabricUID: 1618
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/ingest_customers
    - pipelines/cleanup_orders
    - pipelines/cleanup_customers
    - pipelines/mrr_reporting
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2023-08-08 19:30:30'
    author: maciej@prophecy.io
    models: []
    sqlProjects: []
  jobs/monthly_job_airflow:
    name: monthly_job_airflow
    description: ''
    fabricUID: 7627
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 1 * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/ingest_customers
    - pipelines/cleanup_orders
    - pipelines/mrr_reporting
    - pipelines/cleanup_customers
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2023-08-08 19:31:06'
    author: maciej@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-03-24 19:20:44'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs:
  subgraphs/enrich_customers:
    name: enrich_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2022-09-29 03:48:30'
  subgraphs/data_cleanup:
    name: data_cleanup
    description: ''
    author: maciej+webinar-2022@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2023-02-17 04:35:57'
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-10-01T19:42:21.429275Z'
  name: plibMaven
  version: 8.2.1
  id: '193641757'
  createdAt: '2024-10-01T19:42:21.429207Z'
- type: plibPypi
  modifiedAt: '2024-10-01T19:42:21.429339Z'
  name: plibPypi
  version: 1.9.16
  id: '1771707623'
  createdAt: '2024-10-01T19:42:21.429322Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.30
    isDefault: true
    author: null
    createdAt: '2024-10-01 20:53:41'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-10-01 20:53:52'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
