name: supercharge_delta_lake
description: ''
version: '79.0'
author: maciej+webinar-2022@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: supercharge_delta_lake
  parentArtefactID: prophecy_webinar
  buildSystem: wheel
  author: null
  createdAt: '2023-03-24 19:20:44'
pipelines:
  pipelines/ingest_customers:
    name: ingest_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:19:30'
    datasets:
      inputs:
      - datasets/raw_customers
      outputs:
      - datasets/bronze_customers
    subgraphs: []
    dependencies: {}
  pipelines/cleanup_customers:
    name: cleanup_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:33:01'
    datasets:
      inputs:
      - datasets/bronze_customers
      outputs:
      - datasets/silver_customers
    subgraphs: []
    dependencies: {}
  pipelines/mrr_reporting:
    name: mrr_reporting
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-10-11 23:15:32'
    datasets:
      inputs:
      - datasets/customer_nations
      - datasets/nation
      - datasets/regions
      - datasets/silver_customers
      - datasets/silver_orders
      outputs:
      - datasets/final_report
    subgraphs:
    - subgraphs/enrich_customers
    dependencies: {}
  pipelines/cleanup_orders:
    name: cleanup_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-29 01:31:06'
    datasets:
      inputs:
      - datasets/bronze_orders
      outputs:
      - datasets/silver_orders
    subgraphs: []
    dependencies: {}
  pipelines/demo_day:
    name: demo_day
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-02-23 18:44:09'
    datasets:
      inputs:
      - datasets/customer_nations
      - datasets/nation
      - datasets/regions
      - datasets/silver_customers
      - datasets/silver_orders
      outputs:
      - datasets/final_table
    subgraphs:
    - subgraphs/enrich_customers
    dependencies: {}
datasets:
  datasets/customer_nations:
    name: customer_nations
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:37:12'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:37:12'
  datasets/regions:
    name: regions
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:35:00'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:35:00'
  datasets/report_gold:
    name: report_gold
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-07 04:03:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-07 04:03:31'
  datasets/report:
    name: report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-24 16:12:02'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Warehouse
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-24 16:12:02'
  datasets/raw_customers:
    name: raw_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:28:34'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:28:34'
  datasets/raw_orders:
    name: raw_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:30:06'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:30:06'
  datasets/gold_report:
    name: gold_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-04 16:02:40'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-04 16:02:40'
  datasets/final_report:
    name: final_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-10-11 23:29:28'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-10-11 23:29:29'
  datasets/silver_orders:
    name: silver_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:32:05'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:32:05'
  datasets/nation:
    name: nation
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 03:35:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 03:35:31'
  datasets/silver_customers:
    name: silver_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:33:40'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:33:40'
  datasets/bronze_customers:
    name: bronze_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:27:10'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:27:10'
  datasets/bronze_orders:
    name: bronze_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-09-29 01:30:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-09-29 01:30:31'
  datasets/department_table:
    name: department_table
    description: ''
    author: maciej@prophecy.io
    createdAt: '2023-08-30 04:58:20'
    mode: batch
    physicalDatasets:
      dev_e2:
        fabricId: 1618
        datasetType: Database
        description: ''
        author: maciej@prophecy.io
        createdAt: '2023-08-30 04:58:20'
templates: {}
jobs:
  jobs/monthly_job_db:
    name: monthly_job_db
    description: ''
    fabricUID: 1618
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/ingest_customers
    - pipelines/cleanup_orders
    - pipelines/cleanup_customers
    - pipelines/mrr_reporting
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2023-08-08 19:30:30'
    author: maciej@prophecy.io
  jobs/monthly_job_airflow:
    name: monthly_job_airflow
    description: ''
    fabricUID: 3346
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 1 * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/ingest_customers
    - pipelines/cleanup_orders
    - pipelines/mrr_reporting
    - pipelines/cleanup_customers
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2023-08-08 19:31:06'
    author: maciej@prophecy.io
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.2.0
  gems: {}
functions:
  author: null
  createdAt: '2023-03-24 19:20:44'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs:
  subgraphs/enrich_customers:
    name: enrich_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2022-09-29 03:48:30'
  subgraphs/data_cleanup:
    name: data_cleanup
    description: ''
    author: maciej+webinar-2022@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2023-02-17 04:35:57'
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: []
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.4
    isDefault: true
    author: null
    createdAt: '2023-09-28 08:42:10'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-09-28 08:42:10'
pipelineConfigurations: {}
