from .bronze_customers import bronze_customers
from .total_spent_by_customer import total_spent_by_customer
from .customer_order_details import customer_order_details
from .bronze_orders import bronze_orders